name: Apoorv Srivastava
description: 5th Year PhD Candidate, Stanford University
avatar: "/assets/images/Apoorv_home.jpg"

footer-links:
  email: apoorv9600@gmail.com
  github: apoorv-s
  linkedin: apoorv-sri
  
plugins:
  - jekyll-katex